### ISSUE TITLE
TODO list for upgrading to b2sdk.v2

### ISSUE THREAD

**Issue by mpnowacki-reef** [Backblaze/B2_Command_Line_Tool#707]
- [x] use new style exceptions in sync, already started in https://github.com/reef-technologies/B2_Command_Line_Tool/pull/68 
- [x] stop using Bucket.copy_file - how to deal with the `--metadataDirective` argument in CLI is yet to be determined (new NBC major release or (more probable) ignoring and issuing a warning)
- [ ] include info on XDG_HOME in help texts
- [x] reimplement `v1.FileVersionInfo.format_ls_entry` and `v1.FileVersionInfo.format_folder_ls_entry` 
- [x] use FileVersion.as_dict(include_auth=True) in GetFileInfo
- [x] use `B2HttpApiConfig` instead of `B2RawApi`
- [x] adjust for new return type in UpdateBucket
